name: node-template-main

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: install dependencies
        run: npm install
      - name: list files
        run: |
          ls ${{ github.workspace }}
      - name: bye step
        run: echo "bue bye"
