name: node-template-main

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test job"
      - name: list files
        run: |
          ls ${{ github.workspace }}
      - name: bye step
        run: echo "bue bye"
